version: '3'

services: 

  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: marcelofelixsalgado/financial-period-api
    container_name: financial-period-api
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30000s /financial-period-api
    ports: 
      - "8082:8082"
    networks: 
      - financial-period-network

    depends_on: 
       - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: financial-period-db
    restart: always
    tty: true
    volumes: 
      - ./scripts/database:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    ports: 
      - "3307:3306"
    environment: 
      - MYSQL_DATABASE=financial_period_db
      - MYSQL_ROOT_PASSWORD=root      
    networks: 
      - financial-period-network

networks: 
  financial-period-network:
    name: financial-period-network
    driver: bridge