version: '3'

services: 

  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: marcelofelixsalgado/financial-period-api
    container_name: financial-period-api
    ports: 
      - "8081:8081"
    networks: 
      - financial-network    
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: financial-db
    restart: always
    tty: true
    volumes: 
      - ./scripts/database:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=financial_db
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - financial-network

networks: 
  financial-network:
    driver: bridge